-- AUTO-GENERATED FULL SCHEMA REBUILD SCRIPT
-- DO NOT EDIT MANUALLY – generated by recovery task
--
-- Execution:
--   docker exec -i stock_postgres psql -U postgres -d Web_quan_li_danh_muc -f /docker-entrypoint-initdb.d/full_rebuild_generated.sql

-- 1) Create financial_oltp schema and core tables
\i '/docker-entrypoint-initdb.d/financial_oltp/tables/001_init_schema.sql'
\i '/docker-entrypoint-initdb.d/financial_oltp/tables/002_create_tables_core.sql'

-- 2) Create market_data_oltp schema and core tables
\i '/docker-entrypoint-initdb.d/market_data_oltp/tables/001_init_schema.sql'
\i '/docker-entrypoint-initdb.d/market_data_oltp/tables/002_create_tables_core.sql'



